In [1]:
import pandas as pd
import numpy as np

In [2]:
%load_ext sql

In [ ]:
# Part 1: Data Loading and Exploration
# Read all CSV files into Pandas DataFrames

In [9]:
df = pd.read_csv('wk8-inventory.csv')

In [ ]:
# Display the first few rows of each DataFrame

In [10]:
print(df.head())

   inventory_id  store_id  product_id  quantity_in_stock last_restock_date  \
0             1         1           1                 25        2022-10-15
1             2         1           5                 42        2022-11-02
2             3         1          10                 18        2022-09-30
3             4         1          15                  5        2022-10-20
4             5         1          20                 12               NaN

   reorder_level
0           10.0
1           15.0
2            8.0
3           10.0
4           15.0

In [11]:
df = pd.read_csv('wk8-sales.csv')
print(df.head())

   sale_id        date  store_id  customer_id  product_id  quantity    total  \
0        1  2022-01-15       3.0           12           5         2    49.98
1        2  2022-01-16       1.0            5          10         1    49.99
2        3  2022-01-18       2.0            8           3         1   349.99
3        4  2022-01-20       4.0           20           7         1   349.99
4        5  2022-01-22       5.0            3          15         1  1599.99

  payment_method
0    Credit Card
1    credit card
2     DEBIT CARD
3           Cash
4             CC

In [12]:
df = pd.read_csv('wk8-stores.csv')
print(df.head())

   store_id         store_name           address         city  state zip_code  \
0         1        City Center   123 Retail Blvd     New York     NY    10001
1         2    Mall of Chicago  456 Shopping Ave      Chicago     IL    60611
2         3  Los Angeles Plaza   789 Commerce St  Los Angeles     CA    90001
3         4   Houston Galleria       321 Main St      Houston  Texas    77002
4         5     Phoenix Outlet     654 Desert Rd      Phoenix     AZ    85001

      region  size_sqft opening_date
0  Northeast    32500.0   2005-05-20
1    Midwest    45000.0   2007-08-15
2       West    55000.0   2004-03-10
3  Southwest        NaN   2008-11-05
4  Southwest    18500.0   2010-06-30

In [13]:
df = pd.read_csv('wk8-products.csv')
print(df.head())

   product_id        product_name     category  subcategory    brand    price  \
0           1     Apple iPhone 13  Electronics  Smartphones    Apple   899.99
1           2  Samsung Galaxy S21  electronics  Smartphones  Samsung   799.99
2           3     Sony WH-1000XM4  ELECTRONICS   Headphones     Sony   349.99
3           4         Dell XPS 13  Electronics      Laptops     Dell  1299.99
4           5    Nike Classic Tee     Clothing       Shirts     Nike    24.99

     cost  weight
0  649.99    0.45
1  539.99    0.50
2  210.00    0.60
3  899.99    2.80
4   12.50    0.20

In [14]:
df = pd.read_csv('wk8-customers.csv')
print(df.head())

   customer_id first_name last_name                  email           phone  \
0            1      James     Smith  james.smith@gmail.com    555-123-4567
1            2       Mary   Johnson                    NaN    212.555.6789
2            3       John  Williams    jwilliams@yahoo.com  (555) 987-6543
3            4   Patricia     Brown     pbrown@hotmail.com      5551234567
4            5     Robert     Jones     rjones23@gmail.com    555-987-3456

        address         city       state    zip_code registration_date
0   123 Main St     New York          NY       10001        2021-03-15
1  456 Park Ave     New York          NY       10022        2020-11-02
2  789 Broadway  Los Angeles  California  90001-1234        2021-05-20
3    321 Elm St      Chicago          IL       60601               NaN
4   555 Pine St      Houston          TX       77002        2020-09-12

In [ ]:
# 2. Exploratory Analysis

# Obtain summary statistics for numerical columns

In [ ]:
# Check for missing values in all dataframes

# Display the data types of each column

In [17]:
df = pd.read_csv('wk8-inventory.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       75 non-null     int64
 1   store_id           75 non-null     int64
 2   product_id         75 non-null     int64
 3   quantity_in_stock  75 non-null     int64
 4   last_restock_date  66 non-null     str
 5   reorder_level      69 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 4.3 KB

In [18]:
df = pd.read_csv('wk8-inventory.csv')
df.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [19]:
df = pd.read_csv('wk8-inventory.csv')
df.shape

(75, 6)

In [20]:
df = pd.read_csv('wk8-sales.csv')

df.info() and df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         40 non-null     int64
 1   date            39 non-null     str
 2   store_id        39 non-null     float64
 3   customer_id     40 non-null     int64
 4   product_id      40 non-null     int64
 5   quantity        40 non-null     int64
 6   total           40 non-null     float64
 7   payment_method  39 non-null     str
dtypes: float64(2), int64(4), str(2)
memory usage: 3.3 KB

In [21]:
df = pd.read_csv('wk8-sales.csv')

df.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [22]:
df = pd.read_csv('wk8-stores.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      15 non-null     int64
 1   store_name    15 non-null     str
 2   address       15 non-null     str
 3   city          15 non-null     str
 4   state         15 non-null     str
 5   zip_code      15 non-null     str
 6   region        15 non-null     str
 7   size_sqft     13 non-null     float64
 8   opening_date  14 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 2.1 KB

In [23]:
df = pd.read_csv('wk8-stores.csv')

df.describe()

        store_id     size_sqft
count  15.000000     13.000000
mean    8.000000  30653.846154
std     4.472136  11342.002717
min     1.000000  16500.000000
25%     4.500000  22000.000000
50%     8.000000  29000.000000
75%    11.500000  35000.000000
max    15.000000  55000.000000

In [24]:
df = pd.read_csv('wk8-products.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     int64
 1   product_name  30 non-null     str
 2   category      30 non-null     str
 3   subcategory   30 non-null     str
 4   brand         30 non-null     str
 5   price         30 non-null     float64
 6   cost          30 non-null     float64
 7   weight        28 non-null     float64
dtypes: float64(3), int64(1), str(4)
memory usage: 3.3 KB

In [25]:
df = pd.read_csv('wk8-products.csv')

df.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [26]:
df = pd.read_csv('wk8-customers.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        31 non-null     int64
 1   first_name         31 non-null     str
 2   last_name          31 non-null     str
 3   email              28 non-null     str
 4   phone              29 non-null     str
 5   address            31 non-null     str
 6   city               31 non-null     str
 7   state              31 non-null     str
 8   zip_code           30 non-null     str
 9   registration_date  28 non-null     str
dtypes: int64(1), str(9)
memory usage: 5.0 KB

In [27]:
df = pd.read_csv('wk8-customers.csv')

df.describe()

       customer_id
count    31.000000
mean     15.838710
std       8.858505
min       1.000000
25%       8.500000
50%      16.000000
75%      23.500000
max      30.000000

In [36]:
# 3. Basic Information Retrieval

# How many unique products are in the product catalog?

df = pd.read_csv('wk8-products.csv')
df['product_id'].count()

np.int64(30)

In [55]:
# What are the top 5 most expensive products?
df = pd.read_csv('wk8-products.csv')
df.sort_values('price', ascending=False)
df.nlargest(5,'price')

,product_id,product_name,category,subcategory,brand,price,cost,weight
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50

In [57]:
# Which store has the largest floor space?
df = pd.read_csv('wk8-stores.csv')
df.nlargest(1,'size_sqft')

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10

In [63]:
# What is the distribution of customers by state?
df = pd.read_csv('wk8-customers.csv')
df['state'] = df['state'].str.replace('California', 'CA')
df['state'] = df['state'].str.replace('North Carolina', 'NC')
df['state'] = df['state'].str.replace('Texas', 'TX')
df['state'] = df['state'].str.replace('Washington', 'WA')
df['state'] = df['state'].str.replace('Oregon', 'OR')
df['state'] = df['state'].str.replace('Maryland', 'MD')
df['state'].value_counts()

state
TX    5
CA    4
NY    2
MD    2
IL    1
AZ    1
PA    1
FL    1
OH    1
NC    1
IN    1
WA    1
CO    1
MA    1
OR    1
NV    1
MI    1
TN    1
KY    1
WI    1
NM    1
MO    1
Name: count, dtype: int64

In [ ]:
# Part 2: Data Cleaning

# 1. Handling Missing Values

# Create copies of original DataFrames for cleaning

In [93]:
# For numerical columns with missing values, replace with column mean
df = pd.read_csv('wk8-stores.csv')
print(df.head())
df_cleaned['size_sqft'] = df['size_sqft'].fillna(df['size_sqft'].mean())
print(df_cleaned)

   store_id         store_name           address         city  state zip_code  \
0         1        City Center   123 Retail Blvd     New York     NY    10001
1         2    Mall of Chicago  456 Shopping Ave      Chicago     IL    60611
2         3  Los Angeles Plaza   789 Commerce St  Los Angeles     CA    90001
3         4   Houston Galleria       321 Main St      Houston  Texas    77002
4         5     Phoenix Outlet     654 Desert Rd      Phoenix     AZ    85001

      region  size_sqft opening_date
0  Northeast    32500.0   2005-05-20
1    Midwest    45000.0   2007-08-15
2       West    55000.0   2004-03-10
3  Southwest        NaN   2008-11-05
4  Southwest    18500.0   2010-06-30
     first_name  last_name           city     size_sqft
0         James      Smith       New York  32500.000000
1          Mary    Johnson       New York  45000.000000
2          John   Williams    Los Angeles  55000.000000
3      Patricia      Brown        Chicago  30653.846154
4        Robert      Jones        Houston  18500.000000
5      Jennifer     Miller        Phoenix  22000.000000
6       Michael      Davis   Philadelphia  35000.000000
7         Linda     Garcia    San Antonio  27500.000000
8       William  Rodriguez      San Diego  42000.000000
9     Elizabeth     Wilson         Dallas  16500.000000
10        David   Martinez       San Jose  29000.000000
11      Barbara   Anderson         Austin  31500.000000
12      Richard     Taylor   Jacksonville  24000.000000
13        Susan     Thomas     Fort Worth  30653.846154
14       Joseph  Hernandez       Columbus  20000.000000
15      Jessica      Moore      Charlotte           NaN
16       Thomas     Martin  San Francisco           NaN
17        Sarah    Jackson   Indianapolis           NaN
18      Charles   Thompson        Seattle           NaN
19        Karen      White         Denver           NaN
20  Christopher      Lopez         Boston           NaN
21        Nancy        Lee       Portland           NaN
22       Daniel   Gonzalez      Las Vegas           NaN
23     Margaret     Harris        Detroit           NaN
24      Matthew      Clark      Nashville           NaN
25        Betty      Lewis      Baltimore           NaN
27       Steven   Robinson     Louisville           NaN
28      Dorothy     Walker      Milwaukee           NaN
29      Anthony      Perez    Albuquerque           NaN
30         Lisa       Hall    Kansas City           NaN

In [81]:
# For categorical columns with missing values, replace with most frequent value
df = pd.read_csv('wk8-stores.csv')

# Unsure

In [76]:
# For date columns with missing values, use forward fill or backward fill as appropriate
df = pd.read_csv('wk8-sales.csv')
df['date'] = df['date'].ffill()
df

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC
5,6,2022-02-01,2.0,17,1,1,899.99,Visa
6,7,2022-02-03,7.0,25,12,2,259.98,PayPal
7,8,2022-02-05,9.0,14,20,1,599.99,Apple Pay
8,9,2022-02-08,10.0,6,4,1,1299.99,Debit
9,10,2022-02-10,3.0,19,9,1,179.99,Cash
10,11,2022-02-15,NaN,22,2,1,799.99,Credit Card
11,12,2022-02-19,5.0,7,18,3,137.97,DC
12,13,2022-02-22,8.0,10,23,2,299.98,cash
13,14,2022-03-01,12.0,2,11,1,199.99,Credit Card
14,15,2022-03-05,15.0,16,6,2,120.48,Debit Card
15,16,2022-03-10,1.0,27,13,3,269.97,paypal
16,17,2022-03-15,3.0,9,27,1,499.99,ApplePay
17,18,2022-03-20,6.0,4,17,4,61.96,Cash
18,19,2022-03-25,9.0,23,21,1,299.99,Credit Card
19,20,2022-04-01,11.0,28,25,2,19.98,CREDIT CARD
20,21,2022-04-05,13.0,12,8,1,99.99,Debit Card
21,22,2022-04-10,2.0,5,19,1,139.99,PP
22,23,2022-04-15,4.0,15,14,3,59.97,Cash
23,24,2022-04-20,7.0,21,22,2,79.98,Credit
24,25,2022-04-25,10.0,3,16,1,329.99,GooglePay
25,26,2022-05-01,14.0,8,24,1,199.99,Credit Card
26,27,2022-05-05,1.0,18,28,1,129.99,debit card
27,28,2022-05-10,5.0,26,1,1,900.50,Cash
28,29,2022-05-15,9.0,11,7,1,349.99,PayPal
29,30,2022-05-20,3.0,24,9,2,359.98,Debit Card
30,31,2022-05-20,2.0,13,4,1,1299.99,Credit Card
31,32,2022-06-01,6.0,29,26,5,24.95,Cash
32,33,2022-06-05,8.0,1,5,3,67.47,NaN
33,34,2022-06-10,11.0,6,22,1,39.99,Debit Card
34,35,2022-06-15,4.0,17,29,2,159.98,Credit Card
35,36,2022-06-20,7.0,9,10,2,98.98,Cash
36,37,2022-06-25,12.0,27,3,1,349.99,PayPal
37,38,2022-07-01,15.0,20,11,1,199.99,google pay
38,39,2022-07-05,3.0,16,30,2,499.98,Credit Card
39,40,2022-07-10,1.0,5,3,1,349.99,CASH

In [91]:
# Check for and remove any duplicate entries in the customers and products dataframes
df = pd.read_csv('wk8-customers.csv')
df_cleaned = df[['first_name', 'last_name', 'city']].drop_duplicates()  
df_cleaned[['first_name', 'last_name', 'city']]
print(df_cleaned)

     first_name  last_name           city
0         James      Smith       New York
1          Mary    Johnson       New York
2          John   Williams    Los Angeles
3      Patricia      Brown        Chicago
4        Robert      Jones        Houston
5      Jennifer     Miller        Phoenix
6       Michael      Davis   Philadelphia
7         Linda     Garcia    San Antonio
8       William  Rodriguez      San Diego
9     Elizabeth     Wilson         Dallas
10        David   Martinez       San Jose
11      Barbara   Anderson         Austin
12      Richard     Taylor   Jacksonville
13        Susan     Thomas     Fort Worth
14       Joseph  Hernandez       Columbus
15      Jessica      Moore      Charlotte
16       Thomas     Martin  San Francisco
17        Sarah    Jackson   Indianapolis
18      Charles   Thompson        Seattle
19        Karen      White         Denver
20  Christopher      Lopez         Boston
21        Nancy        Lee       Portland
22       Daniel   Gonzalez      Las Vegas
23     Margaret     Harris        Detroit
24      Matthew      Clark      Nashville
25        Betty      Lewis      Baltimore
27       Steven   Robinson     Louisville
28      Dorothy     Walker      Milwaukee
29      Anthony      Perez    Albuquerque
30         Lisa       Hall    Kansas City

In [ ]:
# Explain your approach for identifying duplicates
# There was too much variation in phone, address and state. I reduced the variables to only first, last and city.

In [ ]:
### Discussion Questions

In [ ]:
# What are the key advantages of using Pandas for data cleaning compared to other methods?

# All of the calculations can be handled in the same program.

In [ ]:
# How would your approach to handling missing values differ if the missing data was not random but had a pattern or meaning?

# It depends on the data column and value it has for the company. In a real world application, I would not have flash filled the transaction
# date on a credit card transaction due to legal complications. Additional trends would be a key insight for the business that needs to
# be addressed for business needs. Trends and patterns create key metrics for review.

In [ ]:
# What types of data quality issues might not be immediately visible through simple DataFrame inspection methods?

# Variations in data such as date formatting, phone structure, address variations, etc. On first review, the data could look complete but
# andy variations can create a duplicate result.

In [ ]:
# How would you document your data cleaning process to ensure reproducibility?

# If reviewing the same data on a regular basis, column based cleaning code could be saved into a pastable script to be run on new data.

In [ ]:
# In what scenarios might it be better to remove rows with missing values rather than imputing them?

# I would remove the rows if no transactional value is present. Additionally, I would remove the rows if they are determined to be 
# duplicate values.